apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-lan-tls
  namespace: servarr
spec:
  secretName: qbittorrent-lan-tls
  issuerRef:
    name: homelab-lan-ca
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.lan
  duration: 2160h0m0s
  renewBefore: 720h0m0s
