apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: seerr-traefik
  namespace: servarr
  labels:
    app.kubernetes.io/name: seerr
    app.kubernetes.io/part-of: servarr-stack
spec:
  identityRefs:
    - kind: ServiceAccount
      name: traefik
      namespace: kube-system
