apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: homelab-lan-trust-roots
  labels:
    app.kubernetes.io/part-of: servarr-stack
spec:
  sources:
    - secret:
        name: homelab-trust-anchor
        key: tls.crt
  target:
    configMap:
      key: homelan.crt
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: servarr-stack
