apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: radarr-http
  namespace: servarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/part-of: servarr-stack
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: radarr
  port: http
  proxyProtocol: HTTP/1
