apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: servarr
  labels:
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/part-of: servarr-stack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: flaresolverr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flaresolverr
        app.kubernetes.io/part-of: servarr-stack
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: flaresolverr
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8191
              protocol: TCP
          env:
            - name: LOG_LEVEL
              value: info
            - name: TZ
              value: Europe/Bucharest
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1536Mi
