apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: jellyfin-traefik
  namespace: servarr
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: servarr-stack
spec:
  identityRefs:
    - kind: ServiceAccount
      name: traefik
      namespace: kube-system
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: jellyfin-clients
  namespace: servarr
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: servarr-stack
spec:
  identityRefs:
    - kind: ServiceAccount
      name: seerr
