apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: servarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/part-of: servarr-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
